menu:
  Home: /
  Archive: /archives/
  About: "https://github.com/billzong"

# title: Jeremy's Blog
# keywords: Jeremy,Jeremy Fan,Blog,博客,技术,前端,生活
# description: Jeremy Fan's Blog，14 号院

favicon: /favicon.ico?v=2021

# Copyright Infomation
startyear: 2021
